### PR TITLE
feat: move to ESM

### PR DESCRIPTION
**Pull request by ThomasFKJorna**
Updates all the uniorg packages to use and work with the latest versions of the unified ecosystem, which all solely use Ecmascript modules.

Additionally I added some stricter typings to uniorg-rehype.

Everything works, passes all tests, just need to add a tag!

### CODE REVIEW

**Comment by ThomasFKJorna** [comment]
The other thing left to do is update all the documentation.

**Comment by ThomasFKJorna** [comment]
Okay I will try and fix this later, I'm having the biggest case of "Well it works on my machine" ever grrrr

**Comment by ThomasFKJorna** [comment]
I am going to become the joker

**Comment by ThomasFKJorna** [comment]
Alright I give up for now, maybe you can have a look at why this fails @rasendubi ? I'm going insane

PS. Sorry for all the notifications!

**Comment by rasendubi** [comment]
😂😂😂 sure man, I'll take a look this week. maybe tonight

**Comment by rasendubi** [comment]
uniorg v0.5.0 is now ESM-only 🎉 

@ThomasFKJorna thank you for doing most of the migration, and congrats on your second PR!

**Comment by ThomasFKJorna** [comment]
Fantastic! Did you manage to figure out why the builds were all failing?

**Comment by ThomasFKJorna** [comment]
Oh and sorry for leaving the org cite types in, I was working on that separately but mixed those commits in somehow 😅

**Comment by rasendubi** [comment]
>Fantastic! Did you manage to figure out why the builds were all failing?

well, yeah. there were many issues:
1. Some dependencies have broken semantic versioning, so you couldn't even build master: https://github.com/rasendubi/uniorg/pull/31
2. The `setup-node` github action was outdated, so just setting node version to 16.x didn't work. https://github.com/rasendubi/uniorg/pull/32
3. With node-16, lerna has some bizzare issue when working in CI environment — it simply did not install dependencies. (You could reproduce this with `export CI=1`.) That's why you would see build not finding dependencies and types. Fixed this by forcing `lerna bootstrap --no-ci`.
4. The vercel still used node-12, so org-braindump/org-blog-started jobs failed.

re citation support: I'm absolutely for it! I even started working on it before the war. I don't remember where I stopped, but here are my stashed changes: https://github.com/rasendubi/uniorg/pull/33. You can pick them up (use org-element.el as inspiration) and I'll try to help in a week or two

**Pull request merged**
