### PR TITLE
fix: failed to parse headline tags like ":hello:你好:"

### PR DESCRIPTION
**Pull request by xandeer**

### CODE REVIEW

**Comment by rasendubi** [comment]
Thanks for the PR!

Could you add a test case for this?

I'm also a bit worried that regex is too lax now so it can capture
whitespace and other forbidden characters

**Comment by xandeer** [comment]
> Thanks for the PR! Could you add a test case for this? I'm also a bit worried that regex is too lax now so it can capture whitespace and other forbidden characters

Based on your reminder, I avoided spaces and tabs, but I don’t know how to add tests. Can you help me add tests?

**Comment by xandeer** [comment]
Do we need to check the asterisk at the beginning of the line?

**Comment by rasendubi** [comment]
Hey. Sorry for the long reply. I have added a test case to `parser.spec.ts` file and updated the regex to match Emacs implementation.

Emacs uses the following regex: `"[ \t]+\\(:[[:alnum:]_@#%:]+:\\)[ \t]*$"` in this place which is more strict (e.g., it does not allow punctuation). `^\*` is not required as the current position is after parsing initial stars, todo keyword, priority and comment.

I will release the fix in a second

**Pull request merged**
